// lib/core/constants/ticker_symbols.dart
// ~100 most common NSE large/mid cap company name → symbol mappings

class TickerSymbols {
  TickerSymbols._();

  /// Map of lowercase company name/alias → NSE symbol
  static const Map<String, String> companyToSymbol = {
    'reliance': 'RELIANCE',
    'reliance industries': 'RELIANCE',
    'ril': 'RELIANCE',
    'tcs': 'TCS',
    'tata consultancy': 'TCS',
    'tata consultancy services': 'TCS',
    'infosys': 'INFY',
    'infy': 'INFY',
    'hdfc bank': 'HDFCBANK',
    'hdfcbank': 'HDFCBANK',
    'icici bank': 'ICICIBANK',
    'icicibank': 'ICICIBANK',
    'wipro': 'WIPRO',
    'hcl': 'HCLTECH',
    'hcl technologies': 'HCLTECH',
    'hcltech': 'HCLTECH',
    'bajaj finance': 'BAJFINANCE',
    'bajfinance': 'BAJFINANCE',
    'bajaj finserv': 'BAJAJFINSV',
    'kotak mahindra': 'KOTAKBANK',
    'kotak bank': 'KOTAKBANK',
    'kotakbank': 'KOTAKBANK',
    'axis bank': 'AXISBANK',
    'axisbank': 'AXISBANK',
    'sbi': 'SBIN',
    'state bank': 'SBIN',
    'state bank of india': 'SBIN',
    'larsen': 'LT',
    'larsen and toubro': 'LT',
    'l&t': 'LT',
    'lt': 'LT',
    'itc': 'ITC',
    'hindustan unilever': 'HINDUNILVR',
    'hul': 'HINDUNILVR',
    'hindunilvr': 'HINDUNILVR',
    'maruti': 'MARUTI',
    'maruti suzuki': 'MARUTI',
    'asian paints': 'ASIANPAINT',
    'asianpaint': 'ASIANPAINT',
    'nestle': 'NESTLEIND',
    'nestleind': 'NESTLEIND',
    'ultratech': 'ULTRACEMCO',
    'ultratech cement': 'ULTRACEMCO',
    'sun pharma': 'SUNPHARMA',
    'sunpharma': 'SUNPHARMA',
    'divis': 'DIVISLAB',
    'divis labs': 'DIVISLAB',
    'dr reddy': 'DRREDDY',
    "dr reddy's": 'DRREDDY',
    'drreddy': 'DRREDDY',
    'cipla': 'CIPLA',
    'britannia': 'BRITANNIA',
    'titan': 'TITAN',
    'mahindra': 'M&M',
    'm&m': 'M&M',
    'mahindra and mahindra': 'M&M',
    'power grid': 'POWERGRID',
    'ntpc': 'NTPC',
    'ongc': 'ONGC',
    'coal india': 'COALINDIA',
    'coalindia': 'COALINDIA',
    'adani ports': 'ADANIPORTS',
    'adaniports': 'ADANIPORTS',
    'adani enterprises': 'ADANIENT',
    'adanient': 'ADANIENT',
    'adani green': 'ADANIGREEN',
    'adani power': 'ADANIPOWER',
    'adani total gas': 'ATGL',
    'bajaj auto': 'BAJAJ-AUTO',
    'hero motocorp': 'HEROMOTOCO',
    'heromotoco': 'HEROMOTOCO',
    'eicher motors': 'EICHERMOT',
    'tvs motor': 'TVSMOTOR',
    'tvsmotor': 'TVSMOTOR',
    'tata motors': 'TATAMOTORS',
    'tatamotors': 'TATAMOTORS',
    'tata steel': 'TATASTEEL',
    'tatasteel': 'TATASTEEL',
    'jsw steel': 'JSWSTEEL',
    'jswsteel': 'JSWSTEEL',
    'hindalco': 'HINDALCO',
    'vedanta': 'VEDL',
    'bpcl': 'BPCL',
    'bharat petroleum': 'BPCL',
    'ioc': 'IOC',
    'indian oil': 'IOC',
    'hpcl': 'HPCL',
    'gail': 'GAIL',
    'indus towers': 'INDUSTOWER',
    'bharti airtel': 'BHARTIARTL',
    'airtel': 'BHARTIARTL',
    'bhartiartl': 'BHARTIARTL',
    'jio': 'RELIANCE',
    'tech mahindra': 'TECHM',
    'techm': 'TECHM',
    'mphasis': 'MPHASIS',
    'ltimindtree': 'LTIM',
    'lti': 'LTIM',
    'persistent': 'PERSISTENT',
    'persistent systems': 'PERSISTENT',
    'coforge': 'COFORGE',
    'zomato': 'ZOMATO',
    'swiggy': 'SWIGGY',
    'paytm': 'PAYTM',
    'one 97': 'PAYTM',
    'nykaa': 'NYKAA',
    'fsh': 'NYKAA',
    'policybazaar': 'POLICYBZR',
    'delhivery': 'DELHIVERY',
    'indigo': 'INDIGO',
    'interglobe': 'INDIGO',
    'sbi life': 'SBILIFE',
    'sbilife': 'SBILIFE',
    'hdfc life': 'HDFCLIFE',
    'hdfclife': 'HDFCLIFE',
    'icici prudential': 'ICICIPRULI',
    'icici lombard': 'ICICIGI',
    'star health': 'STARHEALTH',
    'pidilite': 'PIDILITIND',
    'mrf': 'MRF',
    'havells': 'HAVELLS',
    'voltas': 'VOLTAS',
    'blue star': 'BLUESTARCO',
    'dixon': 'DIXON',
    'amber enterprises': 'AMBER',
    'cg power': 'CGPOWER',
    'siemens': 'SIEMENS',
    'abb india': 'ABB',
    'godrej consumer': 'GODREJCP',
    'dabur': 'DABUR',
    'marico': 'MARICO',
    'emami': 'EMAMILTD',
    'colgate': 'COLPAL',
    'berger paints': 'BERGEPAINT',
    'kansai nerolac': 'KANSAINER',
    'zydus': 'ZYDUSLIFE',
    'lupin': 'LUPIN',
    'torrent pharma': 'TORNTPHARM',
    'alkem': 'ALKEM',
    'biocon': 'BIOCON',
    'granules': 'GRANULES',
    'laurus labs': 'LAURUSLABS',
    'dmart': 'DMART',
    'avenue supermarts': 'DMART',
    'trent': 'TRENT',
    'bata': 'BATAIND',
    'page industries': 'PAGEIND',
    'metro brands': 'METROBRAND',
    'campus activewear': 'CAMPUS',
  };

  /// NSE symbols for market indices
  static const List<String> nifty50Symbols = [
    'RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS',
    'WIPRO.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'SBIN.NS', 'LT.NS',
    'ITC.NS', 'HINDUNILVR.NS', 'BAJFINANCE.NS', 'MARUTI.NS', 'ASIANPAINT.NS',
    'NESTLEIND.NS', 'ULTRACEMCO.NS', 'SUNPHARMA.NS', 'TITAN.NS', 'DIVISLAB.NS',
  ];

  /// Market index symbols
  static const Map<String, String> indexSymbols = {
    'NIFTY 50': '^NSEI',
    'SENSEX': '^BSESN',
    'BANK NIFTY': '^NSEBANK',
  };
}
